name: Test Kaggle Script Action Failure

on:
  pull_request:

jobs:
  test_kaggle_action_failure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kaggle API credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          echo "KAGGLE_USERNAME=${KAGGLE_USERNAME}" >> $GITHUB_ENV
          echo "KAGGLE_KEY=${KAGGLE_KEY}" >> $GITHUB_ENV

      - name: Test Kaggle Script Action Failure
        uses: ./
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Test Kaggle Script Action Failure"
          custom_script: |
              python test.py --url "https://jsonplaceholder.typicode.com/nonexistent"

          working_subdir: "tests"
          enable_internet: true
          enable_gpu: true
          enable_tpu: false
          sleep_time: 10

