name: Release on Push to Main

on:
  push:
    branches: [fix-release-workflows]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y jq
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y

      - name: Generate Release Notes
        id: release_notes
        run: |
          notes=$(gh release view --repo ${{ github.repository }} latest --json body --jq .body || echo "New release triggered by push to main branch.")
          echo "::set-output name=notes::$notes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Release Date
        id: release_date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Release ${{ env.RELEASE_DATE }}"
          body: "New release triggered by push to main branch."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}