name: Test Kaggle Script Action

on:
  pull_request:

jobs:
  test_kaggle_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Kaggle Script Action
        uses: KevKibe/kaggle-script-action@v1.0.0
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Test Kaggle Script Action"
          custom_script: 'python test.py --url "https://jsonplaceholder.typicode.com/posts/1"'
          working_subdir: "tests"
          enable_internet: true
          enable_gpu: true
          enable_tpu: false
          sleep_time: 10
